### PR TITLE
hv: mshv: vtl: Don't use copy_from/to_user() when interrupts are disa…

### LINKED ISSUE #33: mshv_vtl_hvcall_call() uses copy_from/to_user() incorrectly
In mshv_vtl_hvcall_call(), the functions copy_from_user() and copy_to_user() are called while interrupts are disabled. This is problematic because referencing user space might take a page fault and cause the thread to be descheduled. That would defeat the purpose of disabling interrupts, which is to ensure that the thread stays on the same CPU and hence can use the per-cpu hypercall argument pages. The implementations of copy_from/to_user() call might_fault(), which in this case will WARN if the kernel is compiled with CONFIG_DEBUG_ATOMIC_SLEEP.

mshv_vtl_hvcall_call() probably needs to allocate (and free) two pages at runtime, and use those as the hypercall input and output pages instead of the per-cpu hypercall pages. Then the local_irq_save/restore() isn't needed, and the usage of copy_from/to_user() will be OK.

### PR DESCRIPTION
**Pull request by saurabh-sengar**
…bled

In mshv_vtl_hvcall_call(), the functions copy_from_user() and copy_to_user() are called while interrupts are disabled. This is problematic because referencing user space might take a page fault and cause the thread to be descheduled. That would defeat the purpose of disabling interrupts, which is to ensure that the thread stays on the same CPU and hence can use the per-cpu hypercall argument pages. The implementations of copy_from/to_user() call might_fault(), which in this case will WARN if the kernel is compiled with CONFIG_DEBUG_ATOMIC_SLEEP.

Fix this by allocating two pages at runtime, and use those as the hypercall input and output pages instead of the per-cpu hypercall pages. Then remove the local_irq_save/restore() as they are not required anymore.

Reported-by: Michael Kelley <mhklinux@outlook.com>
Closes: https://github.com/microsoft/OHCL-Linux-Kernel/issues/33

### CODE REVIEW

File: drivers/hv/mshv_vtl_main.c [hunk 1]
```diff
@@ -2333,24 +2333,28 @@ static int mshv_vtl_hvcall_call(struct mshv_vtl_hvcall_fd *fd,
 		return -EPERM;
 	}
 
-	local_irq_save(flags);
-	in = *this_cpu_ptr(hyperv_pcpu_input_arg);
-	out = *this_cpu_ptr(hyperv_pcpu_output_arg);
+	in = (void *)__get_free_pages(GFP_KERNEL, 0);
+	out = (void *)__get_free_pages(GFP_KERNEL, 0);
```
Comment (mhklinux) [inline drivers/hv/mshv_vtl_main.c]: I don't know how important performance is for mshv_vtl_hvcall_call(), but it would be slightly faster to make a single __get_free_pages() call to get 2 pages, and then assign one to "in" and one to "out". Then you would have a single free_page() call as well.

If you keep the two separate calls to __get_free_pages(), you might instead use the __get_free_page() variant that has only one argument.

The rest of the changes look good to me.

Comment (saurabh-sengar) [reply drivers/hv/mshv_vtl_main.c]: Hi @mhklinux ,

Thanks for your comments.
We had a internal discussion before sending this patch and we agreed on having two different pages, reason being the magnitude of saving is quite small compare to the ease of implementation.

I will change "__get_free_pages" to "__get_free_page" in v2

**Review by mhklinux — APPROVED** [review]
Looks good to me.
